version: '3'

services:
  controller-server:
    container_name: controller-server
    restart: always
    build: .
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
      - "${SOCKET_PORT}:${SOCKET_PORT}"
    volumes:
      - ./static:/app/static
      - ./templates:/app/templates
      - ./.env:/app/.env
      - ./server.py:/app/server.py
